apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-datadog-demo-node-app
  annotations:
    ad.datadoghq.com/eks-datadog-demo-node-app.logs: '[{"source":"nodejs","service":"eks-datadog-demo-node-app"}]'  
  labels:
    tags.datadoghq.com/env: "test"
    tags.datadoghq.com/service: "eks-datadog-demo-node-app"
    tags.datadoghq.com/version: "v1.0.1"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks-datadog-demo-node-app
  template:
    metadata:
      annotations:
        ad.datadoghq.com/eks-datadog-demo-node-app.logs: '[{"source":"nodejs","service":"eks-datadog-demo-node-app"}]'
      labels:
        app: eks-datadog-demo-node-app
        tags.datadoghq.com/env: "test"
        tags.datadoghq.com/service: "eks-datadog-demo-node-app"
        tags.datadoghq.com/version: "v1.0.1"
    spec:
      containers:
        - name: eks-datadog-demo-node-app
          image: bensooraj/eks-datadog-demo-node-app:v1.0.1
          ports:
            - containerPort: 8080
          env:
            - name: PLACEHOLDER
              value: "PLACEHOLDER"
          resources:
            requests:
              cpu: "50m"
              memory: "100M"
            limits:
              cpu: "55m"
              memory: "200M"
          imagePullPolicy: Always
