apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-datadog-demo-node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks-datadog-demo-node-app
  template:
    metadata:
      labels:
        app: eks-datadog-demo-node-app
    spec:
      containers:
        - name: eks-datadog-demo-node-app
          image: bensooraj/eks-datadog-demo-node-app:v1.0.1
          ports:
            - containerPort: 8080
          env:
            - name: PLACEHOLDER
              value: "PLACEHOLDER"
          resources:
            requests:
              cpu: "50m"
              memory: "100M"
            limits:
              cpu: "55m"
              memory: "200M"
          imagePullPolicy: Always
