apiVersion: v1
kind: Service
metadata:
  name: eks-datadog-demo-node-app
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: eks-datadog-demo-node-app
status:
  loadBalancer: {}
